- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'TestSub2(5a9f9434-58a6-4974-9fc5-8b721893674c)'
    subscriptionId: '5a9f9434-58a6-4974-9fc5-8b721893674c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG3'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'