# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

Steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'TestSub2(5a9f9434-58a6-4974-9fc5-8b721893674c)'
    subscriptionId: '5a9f9434-58a6-4974-9fc5-8b721893674c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG3'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    deploymentMode: 'Incremental'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
